### ISSUE TITLE
When will the code & dataset be released ?

### ISSUE THREAD

**Issue by DHG-Dav** [ShuhongChen/bizarre-pose-estimator#1]
Hello, i've been hyped by your paper months ago, i'm working on a GAN to generate pictures based on tags/boxes/pose skeletons/segmentation and extra context, i was hoping to use your code / dataset rather than create one from scratch, but the time pass and i see no update, so i was wondering if you still plan to release these, and when ?
Thank you !

**Comment by ShuhongChen** [comment]
Thanks for your interest/hype for our work.  We're working on the code now so that it's ready by the wacv conference (1st week of Jan); sorry it's taking so long, I meant to get it out sooner but other projects kept getting in the way.

Hopefully this will help your conditional generation task, will be looking forward to your results.

**Comment by DHG-Dav** [comment]
Thank you
