### ISSUE TITLE
run without NVIDIA GPU?

### ISSUE THREAD

**Issue by dangviethieu** [ShuhongChen/bizarre-pose-estimator#6]
Hi, I'm really impressed with your project.
I have a question, that can we run the project with i915 GPU driver? Or Google Colab?
Thank you!

**Comment by ShuhongChen** [comment]
> i915 GPU driver?

Thanks for your interest in our work; I'm assuming you mean cpu?  Supposedly everything should also work without a gpu; the reason we say gpu-only is because cuda devices are hard-coded in some places, but if you change them to cpu it should still work

> Or Google Colab?

Yes colab shouldn't have any issues with this; the model isn't very large and should fit on whatever gpus they have there
