### ISSUE TITLE
Confusion

### ISSUE THREAD

**Issue by zm-bisp** [ShuhongChen/bizarre-pose-estimator#8]
Not familiar with docker. Do I need to install docker first before following all the setup steps? 

BTW, how to run this program on servers without root access, I tried the code:
make/docker_pull
make/shell_docker
but permission denied

thanks
: )

**Comment by ShuhongChen** [comment]
> Do I need to install docker first before following all the setup steps?

Hello, yes you'd need to install docker first; this includes nvidia-docker-2 if you plan on using gpu

> but permission denied

Yeah, I think sudo is hardcoded into the docker parts; to be honest I've never gotten nonsudo docker to work on my machines, unfortunately not familiar with how to use without sudo

What server app are you making?  If you don't need production-quality deployment and you have conda/venv, probably easier to just follow the lines of the dockerfile to create an environment

**Comment by WasedaMagina** [comment]
I installed this repo without docker. 
1. run the demo
2. it will give you an import error like "No module named detectron2"
3. pip install the module and go back to step 1.
>

**Comment by zm-bisp** [comment]
Thanks!
I am using a server in my lab without sudo. I think maybe I can run this on a Windows laptop with a nvdia graphic card?

**Comment by ShuhongChen** [comment]
> Windows laptop with a nvdia graphic card

The repo hasn't been tested on Windows ever, but following @WasedaMagina method will probably work for you; I think most dependencies aren't that out of the ordinary

**Comment by DHG-Dav** [comment]
> > Windows laptop with a nvdia graphic card
> 
> The repo hasn't been tested on Windows ever, but following @WasedaMagina method will probably work for you; I think most dependencies aren't that out of the ordinary

Wait what ? I ran it on windows from the very beginning (issue #5 ), i had zero problem to do it and haven't even needed to edit anything, created an anaconda env, installed the dependencies through PIP... it just worked effortlessly. (win10 with RTX3060 12GB X4)
So... it works on windows i can confirm that ^^
(PS : i didn't update you because my project is taking longer than expected, i'm creating a "digital" database (from blender characters) that automatically retrieve the 3D coordinates of each joint while rendering (for a total of 130ish joints), then i plan to adapt a bit your code to this database, and i'm working on other projects at the same time...)

**Comment by ShuhongChen** [comment]
Cool, thanks for confirming on Windows, glad to hear it works; sounds like an interesting project, please share when ready

**Comment by zm-bisp** [comment]
> > > Windows laptop with a nvdia graphic card
> > 
> > 
> > The repo hasn't been tested on Windows ever, but following @WasedaMagina method will probably work for you; I think most dependencies aren't that out of the ordinary
> 
> Wait what ? I ran it on windows from the very beginning (issue #5 ), i had zero problem to do it and haven't even needed to edit anything, created an anaconda env, installed the dependencies through PIP... it just worked effortlessly. (win10 with RTX3060 12GB X4) So... it works on windows i can confirm that ^^ (PS : i didn't update you because my project is taking longer than expected, i'm creating a "digital" database (from blender characters) that automatically retrieve the 3D coordinates of each joint while rendering (for a total of 130ish joints), then i plan to adapt a bit your code to this database, and i'm working on other projects at the same time...)

Hi, I am trying to pull this off on windows, but having difficulties with installing detectron2. Should I directly pip install detectron2 or there are some tricks to follow? I also tried the cmd lines on detectron2 official website. return weird errors.

**Comment by DHG-Dav** [comment]
To be honest, i don't really remember, i think i already had detectron2 installed for testing it long before trying bizarre-pose-estimator, maybe that's why i had no problem ?
detectron2 has to be installed by hand, check their github maybe.
As far as i remember i just followed the explanations given by Shuhong Chen and it worked, i did nothing special.
Sorry i can't help you more.

**Comment by ShuhongChen** [comment]
> Should I directly pip install detectron2 or there are some tricks to follow?

I remember detectron2 being somewhat annoying to compile from source, but the prebuilt pip was pretty straightforward, (should be this line in the [dockerfile](https://github.com/ShuhongChen/bizarre-pose-estimator/blob/e3841c001b97cfa8d0a6d7972b6f882f9e209874/_env/Dockerfile#L60))

**Comment by ShuhongChen** [comment]
Oh, just saw the prebuilt is linux only... unless you get a linux docker working on windows, you'll probably need to build from source:
https://detectron2.readthedocs.io/en/latest/tutorials/install.html#build-detectron2-from-source
